resources:
  - name: code
    type: git
    source:
      uri: https://github.com/pansystar/DatDotNet
      branch: master
jobs:
  - name: build
    plan:
    - aggregate:
      - get: code
        trigger: true
    - task: compile
      privileged: true
      file: code/Pipeline/compile.yml
